### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by rugk** [nucleus-ffm/foss_warn#1]
It would be great to see this Android app on F-Droid!

[F-Droid](https://f-droid.org/) is an Android app store specifically for free/libre open-source apps. It would be great if your app could be released there, as it is the number one for getting FLOSS Android apps for many people.
F-Droid also builds all apps from source ([optionally even reproducible](https://f-droid.org/en/docs/Reproducible_Builds/)), so downloads from there can be trusted.

The [app developer FAQ](https://f-droid.org/en/docs/FAQ_-_App_Developers/) or [the quick start guide](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) may help you to get started.

BTW a release on F-Droid could also bring some (more) popularity (in case that is intended), as it will show up in the app (new apps are featured there).

**Comment by jugendhacker** [comment]
As this app currently is still in a very beta stage I would suggest to not directly add it to the repo and currently it would also not be possible to do so, because it does not meet all requirements needed for inclusion in the F-Droid main repo. But what could be done is setting up a nightly repo via Github actions which builds the app on every commit. This would allow for rapid testing because users could always test the latest commits without needing to build the app themselves.

**Comment by ramack** [comment]
oh, this is not so nice to hear. Which requirement for f-droid is not satisfied?

**Comment by jugendhacker** [comment]
As there is a FOSS license now, we basically you need a [fastlane filestructure](https://gitlab.com/-/snippets/1895688) and a tagged release that is ready to go (and contains the fastlane structure) and we could release it to F-Droid.

**Comment by nucleus-ffm** [comment]
I have now opened an [RFP](https://gitlab.com/fdroid/rfp/-/issues/2005). FOSS Warn should now meet all the requirements.

**Comment by jugendhacker** [comment]
I created a MR for F-Droid metadata: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10521

**Comment by jugendhacker** [comment]
My MR got reviewed and merged, now we have to wait for the next build cycle and hopefully it should get build.

**Comment by qoheniac** [comment]
There it is, good work!

**Comment by IzzySoft** [comment]
Not it is listed at F-Droid.org – do you want me to keep the app in my repo, or shall I remove it after the usual overlap of about 10 days, @nucleus-ffm?

**Comment by nucleus-ffm** [comment]
There is unfortunately a problem with the version that is now in F-Droid. Because of a plugin the configuration file is always overwritten. So it is not usable. I'm sorry, but we have to wait until the 0.2.8 is built and published in F-Droid. The current version is not built with the latest source code. I had to update the version because of that. I replaced the apk from 0.2.7 but the source code was not updated. Sorry, it will not happen again.

**Comment by nucleus-ffm** [comment]
@IzzySoft please wait until the 0.2.8 is released and then 10 days sounds good.

**Comment by IzzySoft** [comment]
Shit happens (to the best of us). And no problem, I can keep it in my repo as long as you want it there. For now I've added a note to wait for v0.2.8 + 10d.

**Comment by nucleus-ffm** [comment]
Version 0.2.8 is now available on F-Droid. Now it's done.

**Comment by IzzySoft** [comment]
So I shall set the timer now?
