### ISSUE TITLE
App ignore do not disturb

### ISSUE THREAD

**Issue by Tealk** [nucleus-ffm/foss_warn#106]
**Describe the bug**
For me, the notifications ignore the "do not disturb" setting

**To Reproduce**
1. Wait for a notification

**Expected behavior**
Only the exceptions on the "do not disturb" list should be audible

 
**Device :**
 - Device: Pixel 6
 - OS: GraphenOS
 - App-version 0.6.1
 - Battery optimization false

**Comment by nucleus-ffm** [comment]
Thank you for your issue. This behavior is not really a bug, but we need to discuss if we want a different behavior. We use the notification category `Alarm` for alerts, which in default mode is an exception in the `Do Not Disturb` settings. If you disable `Alarm` as an exception in the `Do Not Disturb`-settings, the FOSSWarns notifications will be muted. The question is whether we want that. We could change the category to something like `Message` so that the user can still enable the `Do Not Disturb` setting for some notification channels. @MatsG23 what do you think?

**Comment by Tealk** [comment]
Wouldn't it make sense to simply use normal notifications? Everyone can then decide for themselves in the settings whether Do Not Disturb should be bypassed or not.



> e.g. the workflow tried to achieve through the DND mode.

The trigger for the issue was that I was constantly getting alerts even though I was asleep.

**Comment by nucleus-ffm** [comment]
We have [changed the category](https://github.com/nucleus-ffm/foss_warn/blob/c98831d172e90222a64d83ab200011be9454afe8/lib/class/class_NotificationService.dart#L21) to `Message` in version 0.7.0, which should solve this issue.
