### ISSUE TITLE
Integration of OpenStreetMap

### ISSUE THREAD

**Issue by linux-lukas** [nucleus-ffm/foss_warn#11]
Basically, the idea would be to do it like the NINA app - only with OSM.

**Comment by nucleus-ffm** [comment]
This has been on my list since the beginning. But besides the fact that it would be really a lot of work, the main problem is that I would need an OSM tile server for it. OpenStreetMap data is free for everyone to use. The tile servers are not. But if someone has an idea where I could get the OSM tiles from, I could try to create this map.

**Comment by ramack** [comment]
it's too long that I looked at the licensing stuff of OSM, but wouldn't it be as easy as integrating [osmdroid](https://github.com/osmdroid/osmdroid)?

**Comment by carlnickel** [comment]
Is there any news on this?

**Comment by nucleus-ffm** [comment]
> Is there any news on this?
Yes, the feature is basically fully implemented in the in the `improveCAPParsing` branch. And it was actually already some time ago that I implemented that. But it's missing some polishing and some other changes aren't ready yet. But there will be an OSM integration in the next major release, aka 0.8.0.

I'm currently working on some even more significant changes. I hope (but can not promise anything) that the 0.8.0 will be finished with huge improvements by the end of the year.

**Comment by carlnickel** [comment]
So cool!!
