### ISSUE TITLE
[meta] Own F-Droid Possible for Beta Versions?

### ISSUE THREAD

**Issue by Lukas2112** [nucleus-ffm/foss_warn#15]
Could be made available either via F-Droid itself or via a separate repo for beta versions of FOSS WARN?

**Comment by nucleus-ffm** [comment]
Done. There is now an F-Droid repo for my apps. https://github.com/nucleus-ffm/Nucleus-F-Droid-Repo

**Comment by citizenserious** [comment]
Will this repo still be maintained? Or is it obsolete because of the releases in the offical F-Droid repo? Would be nice to know because of the different signatures (; Thanks a lot.

**Comment by nucleus-ffm** [comment]
I'm not sure if it is still needed? You would just save a few days until the version is available via FDroid. Right now I can't release the 0.2.9 via my repo because of signature issues. I need to look into this more so I can build the apk from different computers with the correct signature, or better yet build it with a github action.
