### ISSUE TITLE
Unusually "high" data usage 

### ISSUE THREAD

**Issue by BluePixel4k** [nucleus-ffm/foss_warn#22]
The app has consumed 233MB of mobile/WiFi data for me over the last 18 days. 
I find that unusually "high", for the fact that only texts are synchronized and no images.

What could be the reason for this? 
Possibly because all messages are always synchronized and not only those for the own location? 
Or it increases significantly with poor cell phone reception?

<img src="https://user-images.githubusercontent.com/77979781/154733665-808d3642-89a2-48cf-bfe3-3cc44c57774f.png" width="300" />

**Comment by obsti8383** [comment]
That is most probably since FOSS Warn uses the well known json-File endpoints for the five different warn services. This means on every update a complete json file with all warnings for Germany is fetched (e.g. https://warnung.bund.de/bbk.mowas/gefahrendurchsagen.json). Fetching these five files every 15 minutes then leads to quite a bit of data usage. 

The NINA app uses another not so well known endpoint that allows to fetch only warnings for specific areas (https://warnung.bund.de/api31). A simple example how to use this API can be found here: https://github.com/bundesAPI/nina-api/blob/main/Beispielcode/Python/ZeigeUeberblickWarnmeldungenFuerGebietscode.py
Drawback here: Only would make sense if the "Alle Meldungen" view would be removed / deactivated.

@nucleus-ffm Nice app, by the way! Thanks for that!

**Comment by stefan-niedermann** [comment]
While I haven't dug into the code, I am asking myself whether some or all of the REST endpoints support `ETag` / `If-None-Match` headers and in case they do, if the FOSS Warn app already makes use of it?

This could drastically reduce the transferred data and increase the performance.

In case the endpoints don't support this, maybe we can raise issues "upstream" then?

**Comment by stefan-niedermann** [comment]
Basically it works like this:

- You do request one and receive response one
- Response one has status code `200` and contains a header field `ETag`
- Store the value of this header
- You do request two with a `If-None-Match` header, the value of the `If-None-Match` header must be the value of the previously received `ETag`
- You will receive *either* a response with http status code `200` and the usual payload (this means something has changed). In this case, again response two will contain an `ETag` header, store the new value
- *Or* you will get response two with status code `304` and *no* payload. This means nothing has changed
- Perform the third request with the most current `ETag` you stored (you will only need the latest and can overwrite old `ETag`s)

**Comment by stefan-niedermann** [comment]
No, that's totally fine. The server response contains the `ETag` header with the value.
The Android client has to attach the `If-None-Match` header  (including the value) in the following requests. You need to send the `If-None-Match` header, that's why it isn't here.

No need to perform a unnecessary `HTTP HEAD` request 🙂

**Comment by nucleus-ffm** [comment]
Thanks to @stefan-niedermann, I think it works now. I was only missing a few `"`.  I have created a pre-release with a test version. It would be interesting to see if the data consumption is really reduced now.

**Comment by BluePixel4k** [comment]
Thank you a lot, I will test it. 
But you will probably only notice a bigger difference when there are many warnings like a month ago.
But I'm curious how much less data it uses now :)

**Comment by stefan-niedermann** [comment]
@nucleus-ffm are those changes included in `0.2.10`, which is already available at F-Droid? Couldn't we close this issue then already?

**Comment by BluePixel4k** [comment]
Hard to estimate how much the data usage has changed for me.
In May I had a consumption of 108MB and in June of 134MB. 
Seems a bit lower than in Feb (there wasn't a full month in the photo above). But in the last few months I have also increased the polling frequency from 15 min to 30 min.

Is the data consumption possibly higher if you often have poor cell phone reception (because I have that problem at work).

**Comment by mainrs** [comment]
The implementation of `etag` definitely lowers data usage on my phone. I additionally wanted to mention https://bund.dev/. All services used by this app provide proper API access. It might be worth investigating if the data usage can further be lowered by using the APIs instead of downloading the JSON files.

**Comment by nucleus-ffm** [comment]
I think with the new API that has been used for a few versions, the data usage should be fine. If not, feel free to reopen this issue.
