### ISSUE TITLE
No automatic start of the service with disabled Status-Benachrichtigung (v0.2.10)

### ISSUE THREAD

**Issue by citizenserious** [nucleus-ffm/foss_warn#42]
The Automatic start (e.g after phone boot up) of the app service with disabled "Status-Benachrichtigung anzeigen" seems to not work anymore in v0.2.10. It was reliable in v0.2.9 though. 
Maybe I am misinterpreting this but the "FOSS Warn ist aktiv" notification only appears when I manually open the app after reboot when "Status-Benachrichtigung anzeigen" is disabled.

**Comment by nucleus-ffm** [comment]
This is perhaps a bit confusing and not perfectly implemented. The notification that shows up when you open the app with status notification disabled is an attempt to implement a foreground service. In hindsight, I realized that it's probably not necessary. The actual periodic fetching of data in the background is now done by an Alarm-manager. If you have status notification disabled, you don't see anything from FOSS Warn until you get an alert. However, you also don't notice if FOSS Warn is working. Right now it seems to work reliably with the Alarm-manager, but I'm still waiting for feedback. However, I'm not completely happy with Alarm-manager because it wakes the device up from doze mode. So maybe there will be more changes where I need a foreground service. So for now, you can ignore the notification. 

If you want to be sure that Alarm Manager is running, you can run with adb `adb shell dumpsys alarm | grep de.nucleus.foss_warn`

**Comment by citizenserious** [comment]
Thank you very much for the explanation (:
