### ISSUE TITLE
There are two Warnstufen: "Extrem" in notifications.

### ISSUE THREAD

**Issue by citizenserious** [nucleus-ffm/foss_warn#45]
Today because of the weather, DWD issued the Warnstufe Extrem for there first time since I use this app.
Oddly enough I heard my default notification sound. When I looked into the settings there appeared a second Warnstufe: Extrem with default settings. Wasn't there before the notification got triggered.

![FOSS Warn](https://user-images.githubusercontent.com/62773866/176780056-2059d2f5-e200-4fc6-8bfa-eb655c9ed05c.png)

**Comment by nucleus-ffm** [comment]
mh this is strange. FOSS Warn translates the severity and uses that as the notification channel here: 

https://github.com/nucleus-ffm/foss_warn/blob/15dd62af8255a0d79433d8fe33d0042c06d6c51e/lib/class/class_NotificationService.dart#L15  and here: 
https://github.com/nucleus-ffm/foss_warn/blob/15dd62af8255a0d79433d8fe33d0042c06d6c51e/lib/services/helperFunctionToTranslateAndChooseColorTyp.dart#L116

but both channels seem to have the same name. So maybe one has one more space. But I can't check that because the warning is no longer online.

**Comment by mainrs** [comment]
You can, for good measure, just trim the string beforehand so this does not happen again. At least I can't think of any downsides this would have.

**Comment by nucleus-ffm** [comment]
the string is now simply trimmed. Hopefully this solves the problem.
https://github.com/nucleus-ffm/foss_warn/blob/970730e2106caab9fd17cae35b91dd8032e4df47/lib/services/helperFunctionToTranslateAndChooseColorTyp.dart#L113

**Comment by citizenserious** [comment]
The problem appeared again, or still exists. I got two notifications with the same name for each warning level, except the "Warnstufe: hinweise" (maybe because it was not triggered yet). The second one only appears if there is a warning triggered.
