### ISSUE TITLE
Broken Status Icons when no space left

### ISSUE THREAD

**Issue by TobiGr** [nucleus-ffm/foss_warn#49]
Hey there!
I am running version 0.4.0 Test 2 (beta) from F-Droid on a phone with increased font size. There is only little space on the right when thr city has a long name.
The stays icons on the right are broken:
![dc952a73-dc7b-4efa-bca0-d8c8668cfbf71660980819018](https://user-images.githubusercontent.com/17365767/185734387-564596c0-9d79-42d8-841c-6739c625e897.png)

**Comment by nucleus-ffm** [comment]
Thanks, I need to tweak the UI a bit. What would you suggest? just wrap the text to the next line or just truncate the name with "..."?

But note that version 0.4.0 was never supposed to be built by F-Droid, that was due to F-Droid's update check that built every version, including previous versions. This is now fixed and version 0.4.0 should (hopefully) be removed soon, so please downgrade in F-Droid or update to version 0.4.1 from Github. I will fix this UI thing and release 0.4.1 then - so it should be on F-Droid soon. There is a small bug with the notification settings in version 0.4.0, so I think you never get a notification for a minor warning.

**Comment by nucleus-ffm** [comment]
The problem should be fixed now.
