### ISSUE TITLE
Size of App/APK

### ISSUE THREAD

**Issue by chris-asdf** [nucleus-ffm/foss_warn#80]
Hi,

What's the reason why the App is so big, >40MB for the latest f-droid build?

All the best
Chris

**Comment by nucleus-ffm** [comment]
If I am honest, I also wondered why the size of the app increased so much with version 0.2.0. I have tried several times to find the reason. Today I did some research again and found the answer. The technical answer is that with Android SDK version 23 

> „the platform can read native libraries without extracting them if they are uncompressed, so they changed the default value of extractNativeLibs manifest attribute. 
If you declare minSdk 23 or higher, building the APK with uncompressed native libraries should save space on devices because: 
APK is compressed before download anyway, so download size doesn't change
after installation, there's only one copy of the library (uncompressed inside APK)“ 

found on [stackoverflow](https://stackoverflow.com/questions/62440105/apk-size-increased-35mb-when-bumping-min-sdk-from-21-to-24/63417612#63417612)

So actually the size should decrease, but if the APK contains several ABIs, the APP size increases because the APK contains libraries for all ABIs.

So the plan would be to create builds with split APKs. But we are not sure if F-Droid supports that yet. For the Github release that would be an option, but people need to know which APK they need and it would be nice to automated that. 

For now, I added `android:extractNativeLibs="true"`. To keep the old behaviour. The app size is now 21 MB again, which is fine from my point of view.
